### PR TITLE
point npm's package.json to this repository

### PR DESCRIPTION
**Pull request by shamrin**
Without this, `uws` npm page is confusing, because "github" link points to C++ implementation repository.

This commit fixes the problem, by linking `uws` npm page to uWebSockets-bindings repo.

https://www.npmjs.com/package/uws

### CODE REVIEW

**Comment by shamrin** [comment]
I've just realised there's was PR #5 very recently which did the reverse patch. I still believe this is more correct, because main uWebSockets repo doesn't even mention Node.js.

**Comment by clintwood** [comment]
@alexhultman, any reason both #5 and #6 were closed and not merged - I had to ask in Gitter where this repo was because there is just no hint of where it is in the [C++ repo](uNetworking/uWebSockets).

**Comment by shamrin** [comment]
@alexhultman I've had the same problem as @clintwood had. I've noticed `"uws"` as a dependency in some random project. I haven't heard of uws before and so I decided to learn more about it. However, I couldn't do it easily, because:

google -> "npm uws" -> [uws npm page][npm] -> [C++ repo][c++] -> not even a mention of Node.js

At that point I've even thought that the project is closed source.

[npm]: https://www.npmjs.com/package/uws
[c++]: https://github.com/uNetworking/uWebSockets

**Comment by alexhultman** [comment]
Please stop using the PR tracker as a chat. A closed PR means "no".

**Comment by clintwood** [comment]
@alexhultman, I'm not chatting but asking for a legitimate, rational reason for your closing 2 sensible PRs.  I really just don't get you in respect of your responses to well intentioned rational issues...
Good luck with life!

**Comment by alexhultman** [comment]
@clintwood aaaaand you're permanently blocked..

**Pull request closed without merging**
